name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to EC2
      run: |
        scp -i ~/.ssh/id_rsa -r ./ myuser@your-ec2-ip:/path/to/deploy/

    - name: SSH into EC2 and deploy
      run: |
        ssh -o StrictHostKeyChecking=no myuser@your-ec2-ip << 'EOF'
          cd /path/to/deploy/
          npm install
          pm2 start app.js --name my-app
        EOF
