name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy application to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@3.87.98.197 << 'EOF'
            sudo apt update
            sudo apt install -y nodejs npm
            git clone https://github.com/antoruizx/EC2-desafio-m5.git app || (cd app && git pull)
            cd app
            npm install
            nohup node index.js &
          EOF
