name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Manteniendo el nombre del secreto sin cambios

    - name: Set up SSH private key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa 
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 3.87.98.197 >> ~/.ssh/known_hosts

    - name: Copy files to EC2
      run: |
        scp -i ~/.ssh/id_rsa -r ./ ubuntu@3.87.98.197:/home/ubuntu/EC2-desafio-m5/

    - name: SSH into EC2 and deploy
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@3.87.98.197 << 'EOF'
          cd /home/ubuntu/EC2-desafio-m5/
          npm install
          pm2 start index.js --name my-app

          sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 3001
          sudo ufw allow 80/tcp
          sudo ufw allow 443/tcp
          sudo ufw reload

          pm2 restart my-app
        EOF
